### ISSUE TITLE
Project kan verlengd worden naar een datum in het verleden

### ISSUE THREAD

**Issue by Thomasjanssens001** [itenium-be/confac#230]
Link project 1: http://itenium.synology.me:9100/projects/640092e0079cf99a71d22cea
Link verlengd project:  http://itenium.synology.me:9100/projects/640093fe079cf952a7d22ceb
## **Visual**
![image](https://user-images.githubusercontent.com/126571964/225329380-f38c4f4b-5409-414d-8b35-17a34c3fb7d4.png)
## **Steps to reproduce**
1. Navigeer naar Projectentab
2. Klik op "+ nieuw project" en maak een nieuw project aan
3. Klik rechtsonder op de knop "verlenging"
4. Zet datum "Eind Project" op een datum die voor het begin van het project valt
## **Expected behaviour**
Dit mag niet mogelijk zijn
## **Actual behaviour**
De verlenging wordt aangemaakt waarbij het einde van het project voor het begin van het project plaatsvindt

**Comment by Laoujin** [comment]
Workaround:
- Don't do this...
- Or: Adjust the dates after creation.

Maybe the "real" problem is that the endDate cannot be before the startDate
But this should always be the case, not just when doing a "Verlenging"?

**Comment by Thomasjanssens001** [comment]
Klopt, kan er niets aangepast worden zodat dit niet meer kan? Of misschien kunnen we een waarschuwing toevoegen wanneer de einddatum van een project voor de begindatum valt?

**Comment by Laoujin** [comment]
@Thomasjanssens001 : De titel van deze bug: "Project kan verlengd worden naar een datum in het verleden" zegt momenteel iets dat:
* Wel mogelijk moet zijn (dit komt in praktijk voor)
* Niet overeenkomt met de inhoud van de bug report zelf

**Expected behaviour & Actual behaviour**  
Ik zou dat hier volledig durven weglaten. Het geeft geen meerwaarde, het is onnodige proza.
Let op dat ik zeg "**hier**". Die twee zijn voor veel bug reports noodzakelijk. Hier niet, je kan vb doen:

_Zet datum "Eind Project" op een datum die voor het begin van het project valt_
voeg daar toe, vb:
* --> Disable de button zodat niet kan bewaard worden
* --> Toon een foutboodschap / zet het inputveld in het rood, ... 

Je zou de tekst ook nog kunnen inkorten:
_Zet "Eind Project" voor "Begin Project" --> disable de save button_

**Comment by Laoujin** [comment]
Na wat onderzoek, er zijn hier veel meer bugs dan die ene:

- Geen checks op begin/eind datum bij aanmaak project
- Geen checks op begin/eind datum bij verlenging project
- Geen check dat de verlenging NA de oorspronkelijke project eind datum begint <-- dat is wat is momenteel gerapporteerd


![image](https://user-images.githubusercontent.com/2582910/232339458-ac635436-e788-45fc-99ad-7eb920b51075.png)
